#!/usr/bin/env python
# coding: utf-8
"""
write_adj.py

Code to write ECCOv4r4 Denmark Strait Freshwater Flux adjoint sensitivities to netcdf.

This code requires adxx_*.0000000129.data, generated by running the ECCOv4r4 solution using the masks DenmarkStrait_mask* generated using generate_masks.py and modified code found in https://doi.org/10.5281/zenodo.17225253, generated from adjoint sensitivity experiments as described in Boland et al. 2026

Required to reproduce data for Boland et al. 2026 (in prep)
See https://github.com/emmomp/CANARI_FWTRANS for details

Updated Jan 2026

@author: emmomp@bas.ac.uk Emma J D Boland
"""
import sys
import calendar
from datetime import date
import numpy as np

sys.path.insert(0, "/users/emmomp/Python/ECCOv4-py")
sys.path.insert(0, "/users/emmomp/Python")
import xadjoint as xad
from inputs import EXPDIR, GRIDDIR, eyears, imth

attrs = {
    "contact": "emmomp@bas.ac.uk",
    "references": "ECCOv4r4 Denmark Strait FW flux reconstructions from Boland\
       et al. (inprep)",
    "date": "Created on " + date.today().strftime("%d/%m/%Y"),
    "notes": "Data produced by analysis of the ECCOv4r4 global ocean state estimate,\
       see ecco-group.org",
}

startdates = {"2000": "1996-01-01", "2006": "2002-01-01", "2014": "2010-01-01"}

NT_ADJ = 260
ADJFREQ = 604800

mth_num = [3, 6, 9, 12]

for eyear in eyears:
    STARTDATE = startdates[eyear]

    for iem in mth_num:
        expt = f"ad_5y_denstr_horflux_fw_{imth[iem]}_noparam_7d_{eyear}/"
        print(expt)
        lag0 = np.datetime64(
            f"{eyear}-{iem:02.0f}-{calendar.monthrange(int(eyear),iem)[1]}"
        )
        print(f"start date {STARTDATE}, lag 0 {lag0}")

        myexp = xad.Experiment(
            GRIDDIR,
            f"{EXPDIR}/{expt}",
            start_date=STARTDATE,
            lag0=lag0,
            nt=NT_ADJ,
            adj_freq=ADJFREQ,
        )
        myexp.load_vars(["adxx_qnet", "adxx_tauu", "adxx_tauv", "adxx_empmr"])
        myexp.data["adxx_tauu"] = -myexp.data["adxx_tauu"].rename({"i_g": "i"})
        myexp.data["adxx_tauv"] = -myexp.data["adxx_tauv"].rename({"j_g": "j"})

        myexp.data = myexp.data.assign_coords(
            {"month": iem, "year": eyear, "fc": myexp.fc}
        ).swap_dims({"time": "lag_years"})
        myexp.to_nctiles(split_timesteps=False)
